apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: advikbalan2709/api:latest
        ports:
        - containerPort: 4000
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:4000"
        - name: DOTNET_RUNNING_IN_CONTAINER
          value: "true"
        - name: DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
          value: "false"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"